apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.projectName }}
  description: ${{ values.description }}
spec:
  type: infrastructure
  owner: user:guest
  lifecycle: production
